
BEGIN BATCH
  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
  VALUES (uuid(), 1, 'My first rafting', 'Sport', 'adventure', 'rafting', 'rafting, extreme sport, Marmore rafting, Marmore', 'media-cell article hentry', 
'http://danieleautizi.local/images/pages/adventure/rafting_04-cover.jpg', '', 'Rafting Marmore', 'http://local.danieleautizi.com:9090/danieleautizi/adventure/rafting/my_first_rafting-1.html', 
'http://danieleautizi.local/pages/adventure/my_first_rafting-1.html', 'My first rafting experience', 'article', '', 'ajax', '2016-05-15 12:18:00', 1, 1);

  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
    VALUES (uuid(), 2, 'Locker Room as life style', 'Life style', 'adventure', 'lockerroom', 'locker room, sport, group, team, football, beach soccer, beach sport, beach volley', 'media-cell article hentry', 
'http://danieleautizi.local/images/pages/adventure/asd_monte_san_giovanni-cup1-cover.jpg', '', 'Locker room concept', 'http://local.danieleautizi.com:9090/danieleautizi/adventure/lockerroom/locker_room_as_life_style-2.html', 
'http://danieleautizi.local/pages/adventure/locker_room_as_life_style-2.html', 'Locker room as life style', 'article', '', 'ajax', '2016-05-15 17:26:00', 3, 1);

  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
    VALUES (uuid(), 3, 'Jumping into the falls', 'Sport', 'adventure', 'rafting', '', 'media-cell video hentry', 
'http://danieleautizi.local/images/pages/adventure/rafting_02-cover.jpg', '', 'Rafting Marmore Video', '', '', '', 'video', '', 'lightbox mfp-iframe', '2016-05-14 11:05:00', 5, 1);

  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
    VALUES (uuid(), 4, 'Mysterious China', 'Travel', 'adventure', 'travel', 'china, beijing, shanghai, trip, travel, the great wall', 'media-cell media image hentry', 
'http://danieleautizi.local/images/pages/adventure/china/birds_nest-background-beijing-cover.jpg', '', 'The Bird s Nest stadium, Beijing - China', '', 'The Bird s Nest stadium, Beijing - China', 
'travel', 'photogallery', 'photogallery', 'lightbox', '2016-05-21 19:15:00', 4, 1);

  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
    VALUES (uuid(), 5, 'Bruxelles & Bruges', 'Travel', 'adventure', 'travel', 'bruxelles, bruges, belgium, trip, travel', 'media-cell media image hentry photogallery', 
'http://danieleautizi.local/images/pages/adventure/belgium/marta_daniele-bruges-cover.jpg', '', 'Bruges, Belgium', '', 'Marta and Daniele in Bruges, Belgium', 
'travel', 'photogallery', 'photogallery', 'lightbox', '2016-05-21 11:21:00', 2, 1);

  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
    VALUES (uuid(), 6, 'Shanghai World Financial Center', 'Travel', 'adventure', 'travel', 'shanghai world financial center, skyscraper, shanghai, china, highest', 'media-cell video hentry', 
'http://danieleautizi.local/images/pages/adventure/china/Shanghai-World-Financial-Center-1-cover.jpg', '', 'Shanghai World Financial Center', '', '', 'On top of the Shanghai World Financial Center', 'video', '', 'lightbox mfp-iframe', '2016-05-22 09:38:00', 6, 1);

  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
    VALUES (uuid(), 7, 'The perfect Bavaria', 'Travel', 'adventure', 'travel', 'bavaria, bayern, baviera, germany, germania, munich, füssen, nuremberg, dachau', 'media-cell media image hentry photogallery', 
'http://danieleautizi.local/images/pages/adventure/bavaria/schloss-panoramic-view-fussen-cover.jpg', '', 'Füssen, Nuremberg, Munich - Bavaria - Germany', '', 'The perfect Bavaria', 'travel', 'photogallery', 'photogallery', 'lightbox', '2016-05-24 09:19:00', 7, 1);

  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
    VALUES (uuid(), 8, 'My favourite Kobenhavn', 'Travel', 'adventure', 'travel', 'copenhagen, denmark, nyhavn, christiania, kobenhavn', 'media-cell media image hentry photogallery', 
'http://danieleautizi.local/images/pages/adventure/copenhagen/copenhagen-skyview-denmark-cover.jpg', '', 'Copenhagen - Denmark', '', 'My favourite Kobenhavn', 'travel', 'photogallery', 'photogallery', 'lightbox', '2016-05-28 14:59:00', 8, 1);

  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
    VALUES (uuid(), 9, 'Crossing the Oresund bridge', 'Travel', 'adventure', 'travel', 'Oresund bridge, copenhagen, malmö, bridge', 'media-cell video hentry', 
'http://danieleautizi.local/images/pages/adventure/copenhagen/oresund_bridge-2048x1280.jpg', '', 'Oresund bridge', '', '', 'Crossing the Oresund bridge', 'video', '', 'lightbox mfp-iframe', '2016-05-30 08:47:00', 9, 1);
    
  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
    VALUES (uuid(), 10, 'Wonderland Amsterdam', 'Travel', 'adventure', 'travel', 'amsterdam, the netherland', 'media-cell media image hentry photogallery', 
'http://danieleautizi.local/images/pages/adventure/amsterdam/amsterdam-channel-feb_2016-cover.jpg', '', 'Amsterdam - The Netherlands', '', 'Wonderland Amsterdam', 'travel', 'photogallery', 'photogallery', 'lightbox', '2016-05-28 15:00:00', 10, 1);
    
  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
    VALUES (uuid(), 11, 'Tallinn, a pleasant discovery', 'Travel', 'adventure', 'travel', 'tallinn, estonia, openair museum, merchants hotel, oldest pharmacy', 'media-cell media image hentry photogallery', 
'http://danieleautizi.local/images/pages/adventure/tallinn/panoramic_view-tallinn-cover.jpg', '', 'Tallinn - Estonia', '', 'Tallinn, a pleasant discovery', 'travel', 'photogallery', 'photogallery', 'lightbox', '2016-05-28 15:00:00', 11, 1);
    
  INSERT INTO daniele_autizi.adventure (adv_uuid, adv_id, adv_title, adv_category, adv_section, adv_tag, adv_keywords, adv_css_class, adv_image, adv_icon, adv_alt_image, adv_article_url, adv_static_url, 
adv_description, adv_adventure_type, adv_view_type, adv_media_css_class, adv_datetime, adv_prg, adv_active) 
    VALUES (uuid(), 12, 'Warsaw', 'Travel', 'adventure', 'travel', 'warsaw, poland', 'media-cell media image hentry photogallery', 
'http://danieleautizi.local/images/pages/adventure/warsaw/old_town-warsaw.jpg', '', 'Warsaw, poland', '', 'Warsaw', 'travel', 'photogallery', 'photogallery', 'lightbox', '2016-05-28 15:00:00', 12, 1);
APPLY BATCH;


